
testImgs(   'test1.tif', ...
		  	'test2.tif', ...
		  	'test6.tif', ...
            'test_image_2.tif', ...
            'NA.SU3.210.tiff', ...
            'KA.SU2.37.tiff', ...
            'NM.NE1.92.tiff', ...
            'KR.NE1.71.tiff',...
            'NA.NE3.201.tiff'...
		  	)
